<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Input Penanaman · Eka Janma, Eka Taru</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
    <style>body{background:#f4f8f5;color:#173129}.wrap{max-width:1040px;margin:0 auto;padding:2rem 1rem 4rem}.brand{color:#176246;font-weight:800;letter-spacing:-.03em}.topbar{display:flex;align-items:center;justify-content:space-between;margin-bottom:1.7rem}.card{border:1px solid #deebe2;border-radius:20px;box-shadow:0 8px 28px rgba(23,70,50,.05)}.card-header{padding:1.25rem 1.35rem;border-bottom:1px solid #e2ebe6;background:#fff;border-radius:20px 20px 0 0}.form-label{font-size:.78rem;font-weight:700}.form-control,.form-select{padding:.72rem .85rem;border-color:#dce8df;border-radius:10px}.form-text{color:#83928c;font-size:.69rem}.section-label{display:flex;align-items:center;gap:.55rem;margin:1.4rem 0 .85rem;color:#176246;font-size:.75rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.section-label span{display:flex;align-items:center;justify-content:center;width:25px;height:25px;border-radius:8px;color:#fff;background:#176246}.btn-success{border:0;border-radius:10px;background:#176246}.btn-outline-success{border-radius:10px}.map{height:360px;border-radius:13px}.map-help{padding:.7rem .85rem;border-radius:10px;color:#537366;background:#eef8f1;font-size:.7rem}.preview{max-width:100%;max-height:180px;border-radius:10px}.summary{position:sticky;top:1rem}.summary ul{padding:0;margin:0;list-style:none}.summary li{display:flex;gap:.7rem;padding:.75rem 0;border-bottom:1px solid #edf1ee;color:#71837c;font-size:.74rem}.summary li:last-child{border:0}.summary i{color:#2e956c;font-size:1rem}.alert{border:0;border-radius:12px;font-size:.8rem}@media(max-width:767px){.wrap{padding-top:1rem}.topbar{align-items:flex-start;gap:1rem}.summary{position:static}.map{height:290px}}</style>
</head>
<body><main class="wrap"><header class="topbar"><div><div class="brand"><i class="bi bi-tree-fill me-1"></i> Eka Janma, Eka Taru</div><div class="text-muted small mt-1">Form kontribusi penanaman · Provinsi Bali</div></div><span class="badge rounded-pill bg-white text-success border px-3 py-2"><i class="bi bi-shield-check me-1"></i>{{ $accessToken->label }}</span></header>
@if(session('success'))<div class="alert alert-success bg-success-subtle text-success mb-3"><i class="bi bi-check-circle-fill me-1"></i>{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger bg-danger-subtle text-danger mb-3"><i class="bi bi-exclamation-circle-fill me-1"></i>Periksa kembali data yang ditandai sebelum mengirim.</div>@endif
<div class="row g-4"><div class="col-lg-8"><form class="card bg-white" method="POST" action="{{ route('planting.store', ['token' => $token]) }}" enctype="multipart/form-data">@csrf<div class="card-header"><h1 class="h5 fw-bold mb-1">Catat penanaman pohon</h1><p class="text-muted small mb-0">Lengkapi data berikut untuk mendokumentasikan kontribusi Anda.</p></div><div class="card-body p-4">
<div class="section-label"><span>1</span>Identitas penanam</div><div class="row g-3"><div class="col-md-6"><label class="form-label" for="name">Nama lengkap <span class="text-danger">*</span></label><input id="name" name="name" value="{{ old('name') }}" class="form-control @error('name') is-invalid @enderror" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label" for="phone">Nomor telepon <span class="text-danger">*</span></label><input id="phone" name="phone" value="{{ old('phone') }}" class="form-control @error('phone') is-invalid @enderror" placeholder="08xxxxxxxxxx" required>@error('phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label" for="email">Email <span class="text-muted fw-normal">(opsional)</span></label><input type="email" id="email" name="email" value="{{ old('email') }}" class="form-control @error('email') is-invalid @enderror">@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label" for="organization">Instansi / komunitas</label><input id="organization" name="organization" value="{{ old('organization') }}" class="form-control" placeholder="Contoh: DLHK Provinsi Bali"></div><div class="col-md-6"><label class="form-label" for="job_title">Jabatan / peran</label><input id="job_title" name="job_title" value="{{ old('job_title') }}" class="form-control" placeholder="Contoh: Relawan"></div></div>
<div class="section-label"><span>2</span>Detail penanaman</div><div class="row g-3"><div class="col-md-6"><label class="form-label" for="planted_at">Tanggal penanaman <span class="text-danger">*</span></label><input type="date" id="planted_at" name="planted_at" value="{{ old('planted_at', now()->format('Y-m-d')) }}" class="form-control @error('planted_at') is-invalid @enderror" required>@error('planted_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label" for="plant_type">Jenis tanaman <span class="text-danger">*</span></label><select id="plant_type" name="plant_type" class="form-select @error('plant_type') is-invalid @enderror" required><option value="">Pilih jenis tanaman</option>@foreach(['Mahoni','Trembesi','Mangrove','Beringin','Bambu','Nyamplung'] as $type)<option value="{{ $type }}" @selected(old('plant_type') === $type)>{{ $type }}</option>@endforeach</select>@error('plant_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label" for="tree_count">Jumlah pohon <span class="text-danger">*</span></label><input type="number" id="tree_count" name="tree_count" value="{{ old('tree_count') }}" class="form-control @error('tree_count') is-invalid @enderror" min="1" max="10000" placeholder="Contoh: 25" required>@error('tree_count')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label" for="location_name">Nama lokasi</label><input id="location_name" name="location_name" value="{{ old('location_name') }}" class="form-control" placeholder="Contoh: Desa Adat Sanur"></div></div>
<div class="section-label"><span>3</span>Titik lokasi</div><div class="map mb-2" id="planting-map"></div><div class="map-help mb-3"><i class="bi bi-info-circle me-1"></i> Klik titik di peta atau gunakan tombol lokasi Anda. Pastikan pin berada di wilayah Provinsi Bali.</div><div class="row g-3"><div class="col-6"><label class="form-label" for="latitude">Latitude <span class="text-danger">*</span></label><input id="latitude" name="latitude" value="{{ old('latitude') }}" class="form-control @error('latitude') is-invalid @enderror" readonly required>@error('latitude')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-6"><label class="form-label" for="longitude">Longitude <span class="text-danger">*</span></label><input id="longitude" name="longitude" value="{{ old('longitude') }}" class="form-control @error('longitude') is-invalid @enderror" readonly required>@error('longitude')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><button type="button" id="locate" class="btn btn-outline-success btn-sm"><i class="bi bi-crosshair me-1"></i>Gunakan lokasi saya</button><span id="location-status" class="form-text ms-2"></span></div></div>
<div class="section-label"><span>4</span>Dokumentasi</div><label class="form-label" for="photo">Foto tanaman <span class="text-danger">*</span></label><input type="file" id="photo" name="photo" accept="image/jpeg,image/png,image/webp" class="form-control @error('photo') is-invalid @enderror" required><div class="form-text">Format JPG, PNG, atau WEBP. Maksimal 5 MB.</div>@error('photo')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror<img id="photo-preview" class="preview mt-2 d-none" alt="Pratinjau foto dokumentasi"><hr class="my-4"><div class="form-check"><input class="form-check-input @error('consent') is-invalid @enderror" type="checkbox" value="1" id="consent" name="consent" @checked(old('consent')) required><label class="form-check-label small" for="consent">Saya menyatakan data yang diisi benar dan menyetujui penggunaannya untuk dokumentasi program.</label></div>@error('consent')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div><div class="card-footer bg-white border-0 p-4 pt-0"><button type="submit" class="btn btn-success px-4"><i class="bi bi-send me-1"></i>Simpan data penanaman</button></div></form></div>
<div class="col-lg-4"><aside class="card summary bg-white"><div class="card-body p-4"><span class="badge rounded-pill bg-success-subtle text-success mb-3">Cara pengisian</span><h2 class="h6 fw-bold mb-3">Data yang perlu disiapkan</h2><ul><li><i class="bi bi-person-check"></i><span>Identitas dasar penanam dan instansi</span></li><li><i class="bi bi-tree"></i><span>Jenis serta jumlah pohon yang ditanam</span></li><li><i class="bi bi-geo-alt"></i><span>Titik lokasi dari GPS atau peta</span></li><li><i class="bi bi-camera"></i><span>Foto dokumentasi tanaman</span></li></ul><div class="map-help mt-3"><i class="bi bi-shield-lock me-1"></i>Token akses hanya memberi izin untuk mencatat data, bukan melihat data peserta lain.</div></div></aside></div></div></main>
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>document.addEventListener('DOMContentLoaded',()=>{const map=L.map('planting-map').setView([-8.4095,115.1889],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap contributors'}).addTo(map);let marker;const lat=document.getElementById('latitude'),lng=document.getElementById('longitude'),status=document.getElementById('location-status');const setLocation=(point)=>{lat.value=point.lat.toFixed(7);lng.value=point.lng.toFixed(7);if(marker){marker.setLatLng(point)}else{marker=L.marker(point).addTo(map)}status.textContent='Lokasi berhasil dipilih';status.className='form-text ms-2 text-success'};map.on('click',e=>setLocation(e.latlng));document.getElementById('locate').addEventListener('click',()=>{if(!navigator.geolocation){status.textContent='GPS tidak tersedia di perangkat ini';return}status.textContent='Mencari lokasi...';navigator.geolocation.getCurrentPosition(position=>{const point={lat:position.coords.latitude,lng:position.coords.longitude};map.setView(point,15);setLocation(point)},()=>{status.textContent='Lokasi tidak dapat diakses. Periksa izin GPS.'})});document.getElementById('photo').addEventListener('change',event=>{const file=event.target.files[0],preview=document.getElementById('photo-preview');if(file){preview.src=URL.createObjectURL(file);preview.classList.remove('d-none')}})});</script>
@php
    $defaultPlantingLocation = ['location_name' => $accessToken->location_name, 'latitude' => $accessToken->latitude, 'longitude' => $accessToken->longitude];
    $plantTypeOptions = $plantTypes->isNotEmpty() ? $plantTypes->values()->all() : ['Mahoni', 'Trembesi', 'Mangrove', 'Beringin', 'Bambu', 'Nyamplung'];
    $agencyOptions = $agencies->map(fn ($agency) => ['name' => $agency->short_name ?: $agency->name])->values()->all();
@endphp
<script>
document.addEventListener('DOMContentLoaded',()=>{
    const defaults=@json($defaultPlantingLocation);
    const oldLocation=@json(old('location_name')); const oldLatitude=@json(old('latitude')); const oldLongitude=@json(old('longitude'));
    document.getElementById('location_name').value=oldLocation||defaults.location_name||'';
    document.getElementById('latitude').value=oldLatitude||defaults.latitude||'';
    document.getElementById('longitude').value=oldLongitude||defaults.longitude||'';
    const types=@json($plantTypeOptions);
    const typeSelect=document.getElementById('plant_type'); const selected=@json(old('plant_type')); typeSelect.innerHTML='<option value="">Pilih jenis tanaman</option>'+types.map(type=>`<option value="${type}" ${type===selected?'selected':''}>${type}</option>`).join('');
    const agencies=@json($agencyOptions); const organization=document.getElementById('organization'); const selectedAgency=@json(old('organization')); const select=document.createElement('select'); select.id='organization'; select.name='organization'; select.className=organization.className; select.innerHTML='<option value="">Pilih instansi / komunitas</option>'+agencies.map(agency=>`<option value="${agency.name}" ${agency.name===selectedAgency?'selected':''}>${agency.name}</option>`).join(''); organization.replaceWith(select);
});
</script>
</body></html>
