@csrf
<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="name">Nama</label><input id="name" name="name" value="{{ old('name', $user->name ?? '') }}" class="form-control @error('name') is-invalid @enderror" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="email">Email</label><input id="email" type="email" name="email" value="{{ old('email', $user->email ?? '') }}" class="form-control @error('email') is-invalid @enderror" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="password">Password @if (isset($user))<span class="text-muted small">(kosongkan jika tidak diubah)</span>@endif</label><input id="password" type="password" name="password" class="form-control @error('password') is-invalid @enderror" {{ isset($user) ? '' : 'required' }}>@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="password_confirmation">Konfirmasi password</label><input id="password_confirmation" type="password" name="password_confirmation" class="form-control"></div>
    <div class="col-12"><label class="form-label d-block">Role pengguna</label>@forelse ($roles as $role)<div class="form-check form-check-inline"><input class="form-check-input" type="checkbox" name="roles[]" value="{{ $role->id }}" id="role-{{ $role->id }}" @checked(in_array($role->id, old('roles', isset($user) ? $user->roles->pluck('id')->all() : [])))><label class="form-check-label" for="role-{{ $role->id }}">{{ $role->name }}</label></div>@empty<span class="text-muted">Belum ada role.</span>@endforelse</div>
    <div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" @checked(old('is_active', $user->is_active ?? true))><label class="form-check-label" for="is_active">Pengguna aktif</label></div></div>
</div>
