@extends('adminlte::page')

@section('title', 'Manajemen Pengguna')
@section('content_header')
    <div class="d-flex justify-content-between align-items-center"><h3 class="mb-0">Manajemen Pengguna</h3><a href="{{ route('admin.users.create') }}" class="btn btn-primary"><i class="bi bi-person-plus me-1"></i>Tambah pengguna</a></div>
@stop
@section('content')
    @foreach (['success' => 'success', 'error' => 'danger', 'info' => 'info'] as $messageKey => $theme)
        @if (session($messageKey))<div class="alert alert-{{ $theme }} alert-dismissible fade show">{{ session($messageKey) }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>@endif
    @endforeach
    <x-adminlte-card title="Daftar pengguna" icon="bi bi-people" theme="primary">
        <div class="row g-2 mb-3"><div class="col-md-5"><label class="visually-hidden" for="userSearch">Cari pengguna</label><input id="userSearch" type="search" class="form-control" placeholder="Cari nama atau email..."></div><div class="col-md-3"><label class="visually-hidden" for="userStatus">Filter status</label><select id="userStatus" class="form-select"><option value="">Semua status</option><option value="active">Aktif</option><option value="inactive">Nonaktif</option><option value="pending">Menunggu verifikasi</option></select></div><div class="col-md-3"><label class="visually-hidden" for="userRole">Filter role</label><select id="userRole" class="form-select"><option value="">Semua role</option>@foreach ($roles as $role)<option value="{{ $role->slug }}">{{ $role->name }}</option>@endforeach</select></div><div class="col-md-1"><button type="button" id="clearUserFilters" class="btn btn-outline-secondary w-100" title="Reset filter"><i class="bi bi-arrow-counterclockwise"></i><span class="visually-hidden">Reset filter</span></button></div></div>
        <div class="table-responsive"><table id="usersTable" class="table table-hover align-middle mb-0" data-page-size="10"><thead><tr><th data-sort="name">Nama <i class="bi bi-arrow-down-up small"></i></th><th data-sort="email">Email <i class="bi bi-arrow-down-up small"></i></th><th data-sort="created">Terdaftar <i class="bi bi-arrow-down-up small"></i></th><th>Status</th><th>Role</th><th class="text-end">Aksi</th></tr></thead><tbody>
            @forelse ($users as $user)
                <tr data-name="{{ strtolower($user->name) }}" data-email="{{ strtolower($user->email) }}" data-status="{{ $user->is_active ? 'active' : 'inactive' }}" data-verification="{{ $user->email_verified_at ? 'verified' : 'pending' }}" data-role="{{ $user->roles->pluck('slug')->implode(',') }}" data-created="{{ $user->created_at->timestamp }}"><td>{{ $user->name }}</td><td>{{ $user->email }}</td><td>{{ $user->created_at->format('d M Y H:i') }}</td><td>@if (! $user->is_active)<span class="badge text-bg-secondary">Nonaktif</span>@elseif (! $user->email_verified_at)<span class="badge text-bg-warning">Menunggu verifikasi</span>@else<span class="badge text-bg-success">Aktif</span>@endif</td><td>{{ $user->roles->pluck('name')->join(', ') ?: 'Tanpa role' }}</td><td class="text-end text-nowrap">@if (! $user->email_verified_at)<form class="d-inline" action="{{ route('admin.users.verify', $user) }}" method="post">@csrf<button class="btn btn-sm btn-outline-success" title="Verifikasi"><i class="bi bi-person-check"></i><span class="visually-hidden">Verifikasi</span></button></form>@endif <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-sm btn-outline-primary" title="Edit"><i class="bi bi-pencil"></i><span class="visually-hidden">Edit</span></a> <form class="d-inline" action="{{ route('admin.users.toggle-status', $user) }}" method="post">@csrf<button class="btn btn-sm btn-outline-warning" title="{{ $user->is_active ? 'Nonaktifkan' : 'Aktifkan' }}"><i class="bi bi-toggle-{{ $user->is_active ? 'on' : 'off' }}"></i><span class="visually-hidden">{{ $user->is_active ? 'Nonaktifkan' : 'Aktifkan' }}</span></button></form> @if ($user->id !== auth()->id())<form class="d-inline" action="{{ route('admin.users.destroy', $user) }}" method="post" onsubmit="return confirm('Hapus pengguna ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger" title="Hapus"><i class="bi bi-trash"></i><span class="visually-hidden">Hapus</span></button></form>@endif</td></tr>
            @empty
                <tr><td colspan="6" class="text-center text-muted py-4">Belum ada pengguna.</td></tr>
            @endforelse
        </tbody></table></div><div id="userTableFooter" class="d-flex justify-content-between align-items-center mt-3 small text-muted"></div>
    </x-adminlte-card>
@stop
@push('js')
<script>
document.addEventListener('DOMContentLoaded', () => { const table = document.getElementById('usersTable'); if (!table) return; const rows = [...table.querySelectorAll('tbody tr[data-name]')]; const search = document.getElementById('userSearch'); const status = document.getElementById('userStatus'); const role = document.getElementById('userRole'); const footer = document.getElementById('userTableFooter'); let page = 1; let sort = { key: 'created', direction: 'desc' }; const render = () => { const query = search.value.toLowerCase().trim(); const filtered = rows.filter(row => (!query || `${row.dataset.name} ${row.dataset.email}`.includes(query)) && (!status.value || row.dataset.status === status.value || (status.value === 'pending' && row.dataset.verification === 'pending')) && (!role.value || row.dataset.role.split(',').includes(role.value))); filtered.sort((a, b) => (a.dataset[sort.key] > b.dataset[sort.key] ? 1 : -1) * (sort.direction === 'asc' ? 1 : -1)); const pages = Math.max(1, Math.ceil(filtered.length / 10)); page = Math.min(page, pages); rows.forEach(row => { row.hidden = true; }); filtered.slice((page - 1) * 10, page * 10).forEach(row => { row.hidden = false; }); footer.innerHTML = `<span>${filtered.length} pengguna ditemukan</span><span class="btn-group"><button class="btn btn-sm btn-outline-secondary" ${page === 1 ? 'disabled' : ''} data-page="${page - 1}"><i class="bi bi-chevron-left"></i></button><span class="btn btn-sm btn-outline-secondary disabled">${page} / ${pages}</span><button class="btn btn-sm btn-outline-secondary" ${page === pages ? 'disabled' : ''} data-page="${page + 1}"><i class="bi bi-chevron-right"></i></button></span>`; footer.querySelectorAll('[data-page]').forEach(button => button.addEventListener('click', () => { page = Number(button.dataset.page); render(); })); }; [search, status, role].forEach(input => input.addEventListener('input', () => { page = 1; render(); })); document.getElementById('clearUserFilters').addEventListener('click', () => { search.value = ''; status.value = ''; role.value = ''; page = 1; render(); }); table.querySelectorAll('th[data-sort]').forEach(header => header.addEventListener('click', () => { const key = header.dataset.sort; sort = { key, direction: sort.key === key && sort.direction === 'asc' ? 'desc' : 'asc' }; render(); })); render(); });
</script>
@endpush
