@extends('adminlte::page')
@section('title','Jenis Tanaman')
@push('css')<style>.gm-admin-modal .modal-content{overflow:hidden;border:0;border-radius:20px;box-shadow:0 22px 60px rgba(23,70,50,.18)}.gm-admin-modal .modal-header{padding:1.35rem 1.5rem;border-bottom:1px solid #e8efeb;background:#fbfdfb}.gm-admin-modal .modal-body{padding:1.5rem}.gm-admin-modal .modal-footer{padding:1rem 1.5rem 1.35rem;border-top:0}.gm-admin-modal .form-label{margin-bottom:.45rem;color:#365348;font-size:.78rem;font-weight:700}.gm-admin-modal .form-control{min-height:43px;border-color:#dce8df;border-radius:10px}.gm-admin-modal .row{row-gap:1rem!important}.gm-admin-modal hr{margin:1.25rem 0 0;border-color:#edf2ee}</style>@endpush
@section('content_header')<div class="d-flex justify-content-between align-items-center"><div><h3 class="mb-0">Jenis tanaman</h3><span class="text-muted small">Kelola pilihan tanaman pada form publik</span></div><button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#createPlantTypeModal"><i class="bi bi-plus-lg me-1"></i>Tambah jenis</button></div>@stop
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<x-adminlte-card title="Daftar jenis tanaman" icon="bi bi-tree" theme="success">
<div class="row g-2 mb-3"><div class="col-md-6"><label class="visually-hidden" for="plantTypeSearch">Cari jenis</label><input id="plantTypeSearch" type="search" class="form-control" placeholder="Cari jenis atau deskripsi..."></div><div class="col-md-3"><select id="plantTypePageSize" class="form-select"><option value="10">10 per halaman</option><option value="25">25 per halaman</option></select></div></div>
<div class="table-responsive"><table id="plantTypeTable" class="table table-hover align-middle"><thead><tr><th data-sort="name">Nama <i class="bi bi-arrow-down-up small"></i></th><th>Deskripsi</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
@forelse($plantTypes as $type)<tr data-row="{{ strtolower($type->name.' '.$type->description) }}" data-name="{{ $type->name }}"><td class="fw-semibold">{{ $type->name }}</td><td class="text-muted small">{{ $type->description ?: '—' }}</td><td><span class="badge text-bg-{{ $type->is_active ? 'success' : 'secondary' }}">{{ $type->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="text-end"><a href="{{ route('admin.plant-types.edit',$type) }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-pencil"></i></a><form class="d-inline" method="POST" action="{{ route('admin.plant-types.destroy',$type) }}" onsubmit="return confirm('Hapus jenis ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="4" class="text-center text-muted py-4">Belum ada jenis tanaman.</td></tr>@endforelse
</tbody></table></div><div id="plantTypeTableFooter" class="d-flex justify-content-between align-items-center mt-3 small text-muted"></div>
</x-adminlte-card>
<div class="modal fade gm-admin-modal" id="createPlantTypeModal" tabindex="-1" aria-labelledby="createPlantTypeModalLabel" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="createPlantTypeModalLabel"><i class="bi bi-tree text-success me-2"></i>Tambah jenis tanaman</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup"></button></div><form method="POST" action="{{ route('admin.plant-types.store') }}"><div class="modal-body">@include('admin.catalog-form',['kind'=>'plant'])</div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button class="btn btn-success">Simpan jenis</button></div></form></div></div></div>
@stop
@push('js')@include('admin.partials.datatable-script',['tableId'=>'plantTypeTable','searchId'=>'plantTypeSearch','pageSizeId'=>'plantTypePageSize','footerId'=>'plantTypeTableFooter'])@endpush
