@extends('adminlte::page')
@section('title','Data Instansi')
@push('css')<style>.gm-admin-modal .modal-content{overflow:hidden;border:0;border-radius:20px;box-shadow:0 22px 60px rgba(23,70,50,.18)}.gm-admin-modal .modal-header{padding:1.35rem 1.5rem;border-bottom:1px solid #e8efeb;background:#fbfdfb}.gm-admin-modal .modal-body{padding:1.5rem}.gm-admin-modal .modal-footer{padding:1rem 1.5rem 1.35rem;border-top:0}.gm-admin-modal .form-label{margin-bottom:.45rem;color:#365348;font-size:.78rem;font-weight:700}.gm-admin-modal .form-control{min-height:43px;border-color:#dce8df;border-radius:10px}.gm-admin-modal .row{row-gap:1rem!important}.gm-admin-modal hr{margin:1.25rem 0 0;border-color:#edf2ee}</style>@endpush
@section('content_header')<div class="d-flex justify-content-between align-items-center"><div><h3 class="mb-0">Data instansi</h3><span class="text-muted small">Kelola nama Perangkat Daerah dan mitra program</span></div><button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#createAgencyModal"><i class="bi bi-plus-lg me-1"></i>Tambah instansi</button></div>@stop
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<x-adminlte-card title="Daftar instansi" icon="bi bi-building" theme="success">
<div class="row g-2 mb-3"><div class="col-md-6"><label class="visually-hidden" for="agencySearch">Cari instansi</label><input id="agencySearch" type="search" class="form-control" placeholder="Cari nama atau deskripsi..."></div><div class="col-md-3"><select id="agencyPageSize" class="form-select"><option value="10">10 per halaman</option><option value="25">25 per halaman</option></select></div></div>
<div class="table-responsive"><table id="agencyTable" class="table table-hover align-middle"><thead><tr><th data-sort="name">Nama instansi <i class="bi bi-arrow-down-up small"></i></th><th>Nama singkat</th><th>Deskripsi</th><th>Status</th><th class="text-end">Aksi</th></tr></thead><tbody>
@forelse($agencies as $agency)<tr data-row="{{ strtolower($agency->name.' '.$agency->short_name.' '.$agency->description) }}" data-name="{{ $agency->name }}"><td class="fw-semibold">{{ $agency->name }}</td><td>{{ $agency->short_name ?: '—' }}</td><td class="text-muted small">{{ $agency->description ?: '—' }}</td><td><span class="badge text-bg-{{ $agency->is_active ? 'success' : 'secondary' }}">{{ $agency->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="text-end"><a href="{{ route('admin.agencies.edit',$agency) }}" class="btn btn-sm btn-outline-primary"><i class="bi bi-pencil"></i></a><form class="d-inline" method="POST" action="{{ route('admin.agencies.destroy',$agency) }}" onsubmit="return confirm('Hapus instansi ini?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">Belum ada instansi.</td></tr>@endforelse
</tbody></table></div><div id="agencyTableFooter" class="d-flex justify-content-between align-items-center mt-3 small text-muted"></div>
</x-adminlte-card>
<div class="modal fade gm-admin-modal" id="createAgencyModal" tabindex="-1" aria-labelledby="createAgencyModalLabel" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="createAgencyModalLabel"><i class="bi bi-building text-success me-2"></i>Tambah instansi</h5><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Tutup"></button></div><form method="POST" action="{{ route('admin.agencies.store') }}"><div class="modal-body">@include('admin.catalog-form',['kind'=>'agency'])</div><div class="modal-footer"><button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Batal</button><button class="btn btn-success">Simpan instansi</button></div></form></div></div></div>
@stop
@push('js')@include('admin.partials.datatable-script',['tableId'=>'agencyTable','searchId'=>'agencySearch','pageSizeId'=>'agencyPageSize','footerId'=>'agencyTableFooter'])@endpush
